---
title: "DaVisu_Talebi"
author: "Amir_TALEBI"
date: "2022-11-25"
output: html_document
---

```{r library}
library(tidyverse)
library(ggplot2)
library(highcharter) 
library(gganimate)
library(gifski)
library(readr)
library(forecast)
library(dplyr)
library(janitor)
library(reshape)
library(forcats)

##### due to the kind of dataset(s), I have used some special libraries to get my plots ######
```

```{r data}
co2_emission <- read.csv("data/CO2_emission.csv")
death_airPolution <- read.csv("data/death-rates-from-air-pollution.csv")
popu_world <- read.csv("data/world_population.csv")
```

```{r}
data_without_na <- co2_emission %>% 
  replace(is.na(.), 0) 
df <- data_without_na |>
        select(starts_with("X"))
tot_emission <- colSums(df)
year <- c(1990:2019)
custom_clr <- c("#619CFF")
custom_dsh <- c("ShortDashDotDot")
my_df <- data.frame(year, tot_emission)
hc <- hchart(my_df,'line', hcaes(x = year, y = tot_emission),
       color = custom_clr, dashStyle = custom_dsh) |>
  hc_yAxis(title = list(text = "Total emission")) |>  
  hc_xAxis(title = list(text = "Year")) |>
  hc_title(
    text = "Interactive plot for Global Co2 emission (metric tons per capita)",
    margin = 20, 
    align = "center",
    style = list(color = "#FF0000", useHTML = TRUE)
  )
hc
```

```{r}
df = subset(co2_emission, select = -c(country_code, Indicator.Name)) 
dfmelted <- melt(df, id_vars=c('Country', 'Region'), value_vars=c('X1990': 'X2019'), na.rm = TRUE)
colnames(dfmelted)[3] = "Year"
colnames(dfmelted)[4] = "co2_Capita"
dfmelted$Year<-gsub("X","", as.character(dfmelted$Year))

data_new <- dfmelted |>
  filter(Country %in% c("France", "Germany", "Luxembourg", "Belgium"),
         Year >= 2000  , Year <= 2019) |>
  select(Year, Country, co2_Capita)

ggplot(data_new, aes(x = co2_Capita, y = Year, fill = Country)) +
  geom_bar(stat = "identity", width = 0.7) + 
  labs(title = "Stacked bar plots for 4 countries", 
       subtitle = "", 
       caption = "", 
       x = "Co2 emission (metric tons per capita)"
       ) +  
  scale_fill_brewer(palette = "Set3") + 
  theme(axis.title.y = element_blank())
```


```{r}
# I need to do a bit data wrangling to join two tables (Hope its doable), then need also cleaning and joining.
names(co2_emission)[2] <- "Code"
dfnew = subset(co2_emission, select = -c(Region, Indicator.Name)) 
df_long <- melt(data=dfnew, 
                id.vars = c('Country', 'Code'),
                variable_name =  "Year", na.rm = TRUE)
colnames(df_long)[4] = "co2_"
df_long$Year<-gsub("X","",as.character(df_long$Year))
```


```{r}
death_airPolution |>
  group_by(Year) |>
  summarise(total = sum(Air.pollution..total...deaths.per.100.000.)) -> tot1
GData <- ts(tot1[,2], start = 1990, end = 2017, frequency = 1)

fit <- tslm (GData~trend)
fcast <- forecast (fit, h=5)
plot (fcast, xlab ="Year",
ylab ="Total death due to air pollution (in 100,000)",
 col.main ="blue", col = 'red')
lines (fitted (fit))
```


```{r}
```


```{r}
cleandpop <- death_airPolution[!(death_airPolution$Code == ""), ]  ## to remove Oceania with no value for the Code column.
data_mod<- cleandpop %>%                                     
  group_by(Year, Country) %>%
  filter(Year == 2017) %>% 
  top_n(10)
  
##filter(between(Year, 2013, 2014)) 

colnames(data_mod)[4] = "AirPollTotDeathPer100k"
colnames(data_mod)[5] = "InAirPollDeathPer100k"
colnames(data_mod)[6] = "OutParticMatterDeathPer100k"
colnames(data_mod)[7] = "OutOzonePollDeathPer100k"

data_mod

ggplot(data_mod,aes(x=Country,y=Year, fill=AirPollTotDeathPer100k)) +
  geom_bar(position = "stack",stat="identity") + 
  coord_flip()

```


```{r}

df = subset(co2_emission, select = -c(Code, Indicator.Name)) 
dfmelted <- melt(df, id_vars=c('Country', 'Region'), value_vars=c('X1990': 'X2019'),na.rm = TRUE)
colnames(dfmelted)[3] = "Year"
colnames(dfmelted)[4] = "co2_Capita"
dfmelted$Year<-gsub("X","",as.character(dfmelted$Year))

dec_intake_formatted = dfmelted |>
  group_by(Year) |>
  mutate(rank = rank(-co2_Capita),
         Value_rel = co2_Capita/co2_Capita[rank==1],
         Value_lbl = paste0(" ",co2_Capita)) |>
  group_by(Country) |>
  filter(rank <= 10)

anim <- ggplot(dec_intake_formatted, aes(rank, group = Country)) +  
  geom_tile(aes(y = co2_Capita/2,
                height = co2_Capita, fill = Region,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(Country, " ")), vjust = 0.2, hjust = 1, size =7) +
  geom_text(aes(y=co2_Capita,label = Value_lbl, hjust=0), size = 8) +
  coord_flip(clip = "off", expand = TRUE) +
  scale_x_reverse() +
  scale_fill_discrete(guide = guide_legend(title.theme = element_text(
      size = 20), label.theme = element_text(size = 15))) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="red", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="red"),
        plot.caption =element_text(size=14, hjust=0.5, face="italic", color="red"),
        plot.background=element_blank(),
       plot.margin = margin(1,4, 1, 8, "cm")) +
  transition_states(Year, transition_length = 4, state_length = 1) +
  labs(title = 'Top 10 countries for co2 emission. Year: {closest_state}',  
       caption  = "")



library(gifski)
library(png)
animate(anim, nframes = 350,fps = 15,  width = 1200, height = 1000, 
        renderer = gifski_renderer("gganim.gif"))
```





```{r}
```


```{r}
```



```{r}
check_forregion <- co2_emission |>
  group_by(Region, X1990)
check_forregion |>
  ggplot(aes(x = reorder(Region, -X1990), y = X1990, fill=Region)) + 
  geom_violin() + 
  stat_summary(fun = "mean",
               geom = "crossbar", 
               width = 0.5,
               colour = "red") +
    geom_point(position = position_jitterdodge(dodge.width = 0.9),
             alpha = 0.5,
             show.legend = FALSE) +
  coord_flip()+
  theme(legend.position = "none") +
  ggtitle("Year = 1990") + 
  labs(x=" ", y="Metric tone per capita") +
  scale_y_continuous(trans = "sqrt")  
## ggsave("horizontal_violin_plots_ggplot2_R.jpeg")
# we can use fct_reorder or reorder to give order to the violins by ordering the # Violin plot by mean CO2 emission values.
 
```

```{r}
check_forregion <- co2_emission |>
  group_by(Region, X2019)
check_forregion |>
  ggplot(aes(x = reorder(Region, -X2019), y = X2019, fill=Region)) + 
  geom_violin() + 
  stat_summary(fun = "mean",
               geom = "crossbar", 
               width = 0.5,
               colour = "red") +
    geom_point(position = position_jitterdodge(dodge.width = 0.9),
             alpha = 0.5,
             show.legend = FALSE) +
  coord_flip()+
  theme(legend.position = "none") +
  ggtitle("Year = 2019") + 
  labs(x=" ", y="Metric tone per capita") +
  scale_y_continuous(trans = "sqrt")  
## ggsave("horizontal_violin_plots_ggplot2_R.jpeg")
# we can use fct_reorder or reorder to give order to the violins by ordering the # Violin plot by mean CO2 emission values.

```


```{r}
N = 30 # top n rows 
check_for_1990 <- co2_emission |>
  group_by(Country) |>
  filter(!any(is.na(X1990)))

check_for_1990[1:N,] |> 
  group_by(Country, Region) |> 
  arrange(desc(X1990), na.rm =TRUE) |> 
  ggplot(aes(as.factor(Region))) +
  geom_point(aes(y=X1990), colour="red") +   
  theme(axis.text.x = element_text(angle=25, vjust=.5, hjust=1)) +
  labs(y= "Year = 1990 ", x = "Region", title = "co2_emmision metric tons / capita") ## -> sp

```